#!/bin/bash
# Gmail Theme for SoGo — Build Script
# Concatenates src/_*.css into custom-theme.css
#
# Usage:
#   ./build.sh                  → build from src/ only (no generated theme)
#   ./build.sh theme-gen.css    → prepend an extracted Angular Material theme
#
# After building, restart containers:
#   docker compose restart memcached-mailcow sogo-mailcow

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="$SCRIPT_DIR/custom-theme.css"
SRC_DIR="$SCRIPT_DIR/src"
GENERATED_THEME="${1:-}"

echo "Building Gmail theme for SoGo..."
echo ""

# Header comment
cat > "$OUTPUT" <<EOF
/* =============================================================
 * Gmail Theme for SoGo — Mailcow
 * Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit files in src/ and run build.sh to regenerate.
 * =============================================================
 */

EOF

# 1. Prepend Angular Material generated theme CSS (if provided)
if [ -n "$GENERATED_THEME" ] && [ -f "$GENERATED_THEME" ]; then
  echo "/* === Angular Material Generated Theme === */" >> "$OUTPUT"
  cat "$GENERATED_THEME" >> "$OUTPUT"
  printf "\n\n" >> "$OUTPUT"
  echo "  ✓ Prepended Angular Material theme from: $GENERATED_THEME"
elif [ -f "$SCRIPT_DIR/theme-generated.css" ]; then
  echo "/* === Angular Material Generated Theme === */" >> "$OUTPUT"
  cat "$SCRIPT_DIR/theme-generated.css" >> "$OUTPUT"
  printf "\n\n" >> "$OUTPUT"
  echo "  ✓ Prepended Angular Material theme from: theme-generated.css"
else
  echo "  ⚠ No generated Angular Material theme found."
  echo "    To generate it:"
  echo "    1. Set SOGoUIxDebugEnabled = YES in sogo.conf"
  echo "    2. Restart: docker compose restart memcached-mailcow sogo-mailcow"
  echo "    3. Open SoGo in browser, open DevTools console"
  echo "    4. Run: copy([].slice.call(document.styleSheets).map(e=>e.ownerNode).filter(e=>e.hasAttribute('md-theme-style')).map(e=>e.textContent).join('\n'))"
  echo "    5. Paste clipboard into: $SCRIPT_DIR/theme-generated.css"
  echo "    6. Re-run this build script"
  echo ""
fi

# 2. Append source files in order
SOURCE_FILES=(
  "_variables.css"
  "_buttons.css"
  "_header.css"
  "_sidebar.css"
  "_message-list.css"
  "_message-detail.css"
  "_compose.css"
  "_login.css"
  "_calendar.css"
  "_contacts.css"
  "_dialogs.css"
  "_scrollbars.css"
  "_animations.css"
  "_dark-mode.css"
)

for file in "${SOURCE_FILES[@]}"; do
  filepath="$SRC_DIR/$file"
  if [ -f "$filepath" ]; then
    printf "\n" >> "$OUTPUT"
    cat "$filepath" >> "$OUTPUT"
    printf "\n" >> "$OUTPUT"
    echo "  ✓ $file"
  else
    echo "  ⚠ Missing: $file (skipped)"
  fi
done

# Stats
BYTES=$(wc -c < "$OUTPUT")
LINES=$(wc -l < "$OUTPUT")
echo ""
echo "✅ Built: $OUTPUT"
echo "   Size:  $BYTES bytes | $LINES lines"
echo ""
echo "Next steps:"
echo "  docker compose restart memcached-mailcow sogo-mailcow"
